language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release"
